#!/bin/bash

echo "=== Position Distributor Multi-Process Test ==="
echo ""
echo "This script demonstrates the shared memory position distributor"
echo "running across multiple processes."
echo ""
echo "You will need to run the following commands in SEPARATE terminals:"
echo ""
echo "Terminal 1 (Media Driver):"
echo "  cd /Users/lumweiboon/Documents/Github/position_distributor/build"
echo "  ./media_driver"
echo ""
echo "Terminal 2 (BINANCE Publisher):"
echo "  cd /Users/lumweiboon/Documents/Github/position_distributor/build"
echo "  ./test_publisher BINANCE"
echo ""
echo "Terminal 3 (BINANCE Subscriber):"
echo "  cd /Users/lumweiboon/Documents/Github/position_distributor/build"
echo "  ./test_subscriber BINANCE"
echo ""
echo "Terminal 4 (COINBASE Publisher):"
echo "  cd /Users/lumweiboon/Documents/Github/position_distributor/build"
echo "  ./test_publisher COINBASE"
echo ""
echo "Terminal 5 (COINBASE Subscriber):"
echo "  cd /Users/lumweiboon/Documents/Github/position_distributor/build"
echo "  ./test_subscriber COINBASE"
echo ""
echo "Expected behavior:"
echo "- Publishers will send position updates every 2 seconds"
echo "- Subscribers will receive and display those updates in real-time"
echo "- Each exchange operates independently via shared memory topics"
echo "- Press Ctrl+C in any terminal to stop that process"
echo ""
echo "Shared memory files will be created in /tmp/position_distributor_*.dat"
echo ""

# Check if we're in the right directory
if [ ! -f "./media_driver" ]; then
    echo "ERROR: Please run this script from the build directory!"
    echo "cd /Users/lumweiboon/Documents/Github/position_distributor/build"
    echo "chmod +x ../test_multiprocess.sh"
    echo "../test_multiprocess.sh"
    exit 1
fi

echo "Files ready for testing:"
ls -la ./media_driver ./test_publisher ./test_subscriber
echo ""
echo "Ready to start multi-process testing!"
echo "Follow the terminal instructions above."
